services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    expose:
      - 9100

  file-creator-app:
    build: ./file-creator-app
    # volumes:
    #   - ./frontend:/app
    #   # One-way volume to use node_modules from inside image
    #   - /app/node_modules
    ports:
      - "3200:3200"
    environment:
      - NODE_ENV=development
    command: node app.js
