{
 "title": "Server2",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu{ mode=\"system\"})"
    }
   ]
  },
  {
   "title": "CPU monitor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(irate(node_cpu{mode=\"system\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu{mode=\"user\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu{mode=\"nice\"}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu{mode=\"iowait\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu{mode=\"steal\"}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu{mode=\"idle\"}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu{mode=\"irq\"}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"softirq\",instance=~'$node'}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"guest\",instance=~'$node'}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "CPU Historical and Predicted Value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT CONVERT(timestamp, DATETIME) AS time, cpuVal*100  from stockData;"
    },
    {
     "rawSql": "SELECT CONVERT(timestamp, DATETIME) AS time, cpuVal*100  from STOCKnext10;"
    }
   ]
  },
  {
   "title": "Weekly Average",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT week((timestamp)) AS time, avg(cpuVal)*100 from stockData group by week(timestamp);"
    },
    {
     "rawSql": "SELECT week((timestamp)) AS time, avg(cpuVal)*100 from STOCKnext10 group by week(timestamp);"
    }
   ]
  }
 ]
}