FROM python:3.7


WORKDIR /usr/src/app

ENV http_proxy http://web-proxy.in.hpecorp.net:8080
ENV https_proxy http://web-proxy.in.hpecorp.net:8080
ENV no_proxy http://10.163.234.251,localhost,10.163.234.223

COPY ./requirements.txt .
RUN pip install -r requirements.txt
ENV PYTHONUNBUFFERED 1
COPY . .

CMD [ "python", "LSTM.py" ]
