FROM node:latest

WORKDIR /app

COPY package.json .

RUN npm config set proxy http://web-proxy.sgp.hpecorp.net:8080/
RUN npm config set https-proxy http://web-proxy.sgp.hpecorp.net:8080/

RUN npm install

COPY . .

CMD [ "node", "app.js" ]
